server:
  port: 8081

spring:
  application:
    name: client-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gestionbanque_client_service_db
    username: postgres
    password: root1
    # JPA properties

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

topic:
  name: client-event-topic
topic1:
  name1: paiement-event-topic

